apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default "50%" }}
  selector:
    matchLabels:
        {{- include "weather-chart.selectorLabels" . | nindent 6 }}
