name: CI
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install
      - name: Install black
        run: poetry run pip install black
      - name: Install flake8
        run: poetry run pip install flake8

      - name: Lint code
        run: bin/lint   
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t weather-app .

   
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/weather-app:latest   
    
     
